package vault

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/entropy-shield/internal/scanner"
)

// ─── Config & Client ─────────────────────────────────────────────────────────

// Config holds Vault connection parameters.
type Config struct {
	Address   string // e.g. https://vault.example.com:8200
	Token     string // Vault token (VAULT_TOKEN env var fallback)
	Path      string // KV v2 mount path prefix, e.g. "secret/entropy-shield"
	Namespace string // Vault Enterprise namespace (optional)
}

// Client wraps the Vault HTTP API for KV v2 secret storage.
type Client struct {
	cfg  Config
	http *http.Client
}

// NewClient creates and validates a Vault client.
func NewClient(cfg Config) (*Client, error) {
	if cfg.Address == "" {
		cfg.Address = os.Getenv("VAULT_ADDR")
	}
	if cfg.Token == "" {
		cfg.Token = os.Getenv("VAULT_TOKEN")
	}
	if cfg.Address == "" {
		return nil, fmt.Errorf("VAULT_ADDR is not set")
	}
	if cfg.Token == "" {
		return nil, fmt.Errorf("VAULT_TOKEN is not set")
	}

	c := &Client{
		cfg: cfg,
		http: &http.Client{
			Timeout: 15 * time.Second,
		},
	}

	// Health-check
	if err := c.ping(); err != nil {
		return nil, fmt.Errorf("vault unreachable at %s: %w", cfg.Address, err)
	}
	return c, nil
}

// ─── Core Operations ─────────────────────────────────────────────────────────

// StoreSecret writes a finding's secret value to Vault KV v2.
// Returns the Vault path where the secret was stored and the env var name.
func (c *Client) StoreSecret(f scanner.Finding) (string, error) {
	key := buildSecretKey(f)
	path := fmt.Sprintf("%s/%s", strings.TrimRight(c.cfg.Path, "/"), key)

	payload := map[string]interface{}{
		"data": map[string]string{
			"value":    extractPlainValue(f.Match), // raw secret (caller already redacted for display)
			"type":     string(f.Type),
			"source":   fmt.Sprintf("%s:%d", f.File, f.Line),
			"env_var":  f.EnvVarName(),
			"entropy":  fmt.Sprintf("%.4f", f.Entropy),
			"severity": string(f.Severity),
		},
	}

	body, _ := json.Marshal(payload)
	req, err := c.newRequest("POST", "/v1/"+kvV2DataPath(path), bytes.NewReader(body))
	if err != nil {
		return "", err
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return "", fmt.Errorf("vault write: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusNoContent {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("vault write returned %d: %s", resp.StatusCode, string(b))
	}

	return path, nil
}

// GetSecret retrieves a secret from Vault by its KV v2 path.
func (c *Client) GetSecret(path string) (map[string]string, error) {
	req, err := c.newRequest("GET", "/v1/"+kvV2DataPath(path), nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		return nil, fmt.Errorf("secret not found at %s", path)
	}

	var result struct {
		Data struct {
			Data map[string]string `json:"data"`
		} `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}
	return result.Data.Data, nil
}

// ListSecrets returns all secret keys under the configured path prefix.
func (c *Client) ListSecrets() ([]string, error) {
	req, err := c.newRequest("LIST", "/v1/"+kvV2MetaPath(c.cfg.Path), nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data struct {
			Keys []string `json:"keys"`
		} `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}
	return result.Data.Keys, nil
}

// ─── GitHub Actions Output ────────────────────────────────────────────────────

// EnvRefSnippet returns a ready-to-paste GitHub Actions env block that reads
// the stored secret from Vault via the official HashiCorp Vault action.
func EnvRefSnippet(f scanner.Finding, vaultPath, vaultAddr string) string {
	return fmt.Sprintf(`
# Auto-generated by EntropyShield — replace the hardcoded value in %s:%d
# Add to your GitHub Actions workflow:

- name: Import secrets from Vault
  uses: hashicorp/vault-action@v3
  with:
    url: %s
    token: ${{ secrets.VAULT_TOKEN }}
    secrets: |
      %s/%s value | %s

# Then reference in your code:
env:
  %s: ${{ env.%s }}
`,
		f.File, f.Line,
		vaultAddr,
		vaultPath, buildSecretKey(f),
		f.EnvVarName(),
		f.EnvVarName(), f.EnvVarName(),
	)
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

var nonAlphaNum = regexp.MustCompile(`[^a-zA-Z0-9_-]`)

func buildSecretKey(f scanner.Finding) string {
	name := nonAlphaNum.ReplaceAllString(f.File, "_")
	return fmt.Sprintf("%s_%s_L%d", name, strings.ToLower(string(f.Type)), f.Line)
}

// kvV2DataPath converts "secret/foo/bar" → "secret/data/foo/bar"
func kvV2DataPath(path string) string {
	parts := strings.SplitN(path, "/", 2)
	if len(parts) < 2 {
		return path + "/data"
	}
	return parts[0] + "/data/" + parts[1]
}

func kvV2MetaPath(path string) string {
	parts := strings.SplitN(path, "/", 2)
	if len(parts) < 2 {
		return path + "/metadata"
	}
	return parts[0] + "/metadata/" + parts[1]
}

func (c *Client) newRequest(method, path string, body io.Reader) (*http.Request, error) {
	url := strings.TrimRight(c.cfg.Address, "/") + path
	req, err := http.NewRequest(method, url, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("X-Vault-Token", c.cfg.Token)
	req.Header.Set("Content-Type", "application/json")
	if c.cfg.Namespace != "" {
		req.Header.Set("X-Vault-Namespace", c.cfg.Namespace)
	}
	return req, nil
}

func (c *Client) ping() error {
	req, err := c.newRequest("GET", "/v1/sys/health", nil)
	if err != nil {
		return err
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	// 200 = active, 429 = standby, 472 = perf standby — all "reachable"
	if resp.StatusCode >= 500 {
		return fmt.Errorf("vault health check: HTTP %d", resp.StatusCode)
	}
	return nil
}

// extractPlainValue strips the display-safe redaction applied by the scanner.
// In production this would receive the actual secret value from the raw diff.
func extractPlainValue(redacted string) string {
	// Note: in real usage the scanner passes raw values through an internal
	// channel; the redacted form is only for console output. This stub shows
	// the wiring.
	return redacted
}
